### ISSUE TITLE
Rolling back migrations issue

### ISSUE THREAD

**Issue by fullstackhero1** [coderflexx/laravel-ticket#42]
if try to migrate:refresh or migrate:rollback because the down function isn't implemented returns error.

**Comment by fullstackhero1** [comment]
I've made the necessary changes to resolve the problem.

However, when I attempted to push the corrected code to the repository, I encountered a permission issue and I'm unable to proceed with the code submission. I kindly request your assistance in granting me the necessary access to the repository so that I can contribute the fixed code.

I believe that addressing this issue will contribute to the improvement of the package's functionality, and I'm eager to share my solution with the community. Your support in providing access would be greatly appreciated.

Thank you for your time and consideration.

**Comment by ousid** [comment]
Hi @fullstackhero1 

Thank you for addressing the migration issue. If you are unable to create a PR into the repository, please share with us the error code, or where the problem exactly, and how you solve it.

About the permission issue, you can fork the repo, then made the necessary changes, after that you can create a PR directly in the repository. Please be aware of the unit tests check, and if all the tests passes, you are good to go.

Thanks again!

**Comment by ousid** [comment]
Fixed #44 

You can update your package version, and the error should disappear.
