### ISSUE TITLE
Too few arguments to function

### ISSUE THREAD

**Issue by Chrisx84** [coderflexx/laravel-ticket#51]
I keep getting Too few arguments to function when submitting a test ticket.

use Auth;
use Coderflex\LaravelTicket\Models\Ticket;
use Coderflex\LaravelTicket\Models\Category;
use Coderflex\LaravelTicket\Models\Label;
// POST to function store(Request $request)
$user = Auth::user();
$ticket = $user->tickets()->create($request->validate());
$ticket->attachCategories($request->input('category_id'));
$ticket->attachLabels($request->input('label_id'));

Using Laravel 10.something
My fields are exactly like in the database table.
category_id, label_id, priority, title and message.
Sorry but the README is abit vague on what is requested to submit a ticket so im confused.
Thanks.

**Comment by Chrisx84** [comment]
like to add that my user id's uses UUID so had to mod the tables to support varchars

**Comment by ousid** [comment]
Hi, @Chrisx84 

Can you post the full error, please? Your issue seems incomplete.

**Comment by Chrisx84** [comment]
Too few arguments to function Illuminate\Http\Request::Illuminate\Foundation\Providers\{closure}(), 0 passed in /var/www/support/main/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php on line 123 and exactly 1 expected
 
[20240107101805_stacktrace.txt](https://github.com/coderflexx/laravel-ticket/files/13888931/20240107101805_stacktrace.txt)

**Comment by Chrisx84** [comment]
omg i did post my code. thats all the data i have, i log errors to discord using the latest with laravel and your package.
forget it ill add to database using the DB facade.
